services:
  db:
    image: postgres:15
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: softsuave
      POSTGRES_PASSWORD: softsuave
      POSTGRES_DB: usersdb
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  fastapi:
    build: .
    container_name: fastapi_container
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://softsuave:softsuave@db:5432/usersdb
    depends_on:
      - db

volumes:
  postgres_data:
